# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template', '0002_auto_20170516_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='名前')),
                ('src_image', models.ImageField(upload_to='static/data/transaction', verbose_name='画像ファイル')),
                ('dest_image', models.CharField(default=None, max_length=255, null=True, verbose_name='結果画像')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Template', to='template.Templates', verbose_name='テンプレート名')),
            ],
        ),
    ]
