# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.ImageField(upload_to='static/data/', verbose_name='画像ファイル'),
        ),
        migrations.AlterField(
            model_name='images',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='順位'),
        ),
    ]
